DWAPlannerROS:

# Robot Configuration Parameters
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  acc_lim_th: 0.5

  max_vel_trans: 0.8
  min_vel_trans: 0.1
  max_vel_x: 0.8
  min_vel_x: -0.8
  max_vel_y: 0
  min_vel_y: 0

  max_vel_theta: 1
  min_vel_theta: 0.3

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 0.3
  latch_xy_goal_tolerance: true

# Forward Simulation Parameters
  sim_time: 4.0
  sim_granularity: 0.08
  vx_samples: 10
  vy_samples: 0
  vth_samples: 20
  controller_frequency: 2.0

# Trajectory Scoring Parameters
  path_distance_bias: 32
  goal_distance_bias: 20
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
